In [37]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score

from xgboost import XGBRegressor

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
train.isnull().sum()

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [4]:
train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [6]:
train['RoadType'].fillna(method='ffill', inplace=True)

/tmp/ipykernel_1571/3477074788.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['RoadType'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_1571/3477074788.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train['RoadType'].fillna(method='ffill', inplace=True)

In [7]:
test['RoadType'].fillna(method='ffill', inplace=True)

/tmp/ipykernel_1571/300155420.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['RoadType'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_1571/300155420.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test['RoadType'].fillna(method='ffill', inplace=True)

In [8]:
train["Temperature"].fillna(train["Temperature"].median(),inplace=True)

test["Temperature"].fillna(test["Temperature"].median(),inplace=True)

/tmp/ipykernel_1571/2343697827.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["Temperature"].fillna(train["Temperature"].median(),inplace=True)
/tmp/ipykernel_1571/2343697827.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test["Temperature"].fillna(test["Temperature"].median(),inplace=True)

In [9]:
train['Weather'].fillna(method='ffill', inplace=True)

/tmp/ipykernel_1571/1018217306.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Weather'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_1571/1018217306.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train['Weather'].fillna(method='ffill', inplace=True)

In [10]:
test['Weather'].fillna(method='ffill', inplace=True)

/tmp/ipykernel_1571/2673571848.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['Weather'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_1571/2673571848.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test['Weather'].fillna(method='ffill', inplace=True)

In [11]:
train.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         1
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          1
dtype: int64

In [12]:
train['Weather'].fillna(train['Weather'].mode())

0        Sunny
1        Sunny
2        Sunny
3        Rainy
4        Rainy
         ...
77294    Rainy
77295    Foggy
77296    Sunny
77297    Sunny
77298    Snowy
Name: Weather, Length: 77299, dtype: object

In [13]:
train.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         1
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          1
dtype: int64

In [14]:
cat_cols = ["RoadType","Weather"]

for col in cat_cols:
    train[col].fillna(train[col].mode()[0], inplace=True)

    test[col].fillna(test[col].mode()[0], inplace=True)

In [15]:
train.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [16]:
test.isnull().sum()

Index            0
geohash          0
day              0
timestamp        0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

In [17]:
train["hour"] = train["timestamp"].apply(lambda x: int(x.split(":")[0]))

test["hour"] = test["timestamp"].apply(lambda x: int(x.split(":")[0]))

In [18]:
train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour
0,0,qp02z1,48,0:0,0.048804,Residential,1,Not Allowed,No,16.382587,Sunny,0
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny,0
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny,0
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,16.382587,Rainy,0
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy,0

In [19]:
train.tail()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather,hour
77294,77294,qp0d4n,49,2:0,0.067203,Residential,1,Not Allowed,No,11.501664,Rainy,2
77295,77295,qp0d4q,49,2:0,0.022859,Residential,3,Allowed,Yes,14.715254,Foggy,2
77296,77296,qp0d4w,49,2:0,0.141342,Residential,3,Allowed,Yes,19.678860,Sunny,2
77297,77297,qp0dhw,49,2:0,0.087574,Residential,1,Not Allowed,No,22.573958,Sunny,2
77298,77298,qp0djq,49,2:0,0.002944,Residential,3,Allowed,Yes,1.322034,Snowy,2

Peak hour Feature

In [20]:
train["peak_hour"] = train["hour"].apply(lambda x: 1 if 7 <= x <= 10 or 17 <= x <= 20 else 0)

test["peak_hour"] = test["hour"].apply(lambda x: 1 if 7 <= x <= 10 or 17 <= x <= 20 else 0)

Night traffic feature

In [21]:
train["night"] = train["hour"].apply(lambda x: 1 if x >= 22 or x <= 5 else 0)

test["night"] = test["hour"].apply(lambda x: 1 if x >= 22 or x <= 5 else 0)

Encode Categorical columns

In [23]:
cols = ["geohash","RoadType","LargeVehicles","Landmarks","Weather"]

for col in cols:
    le = LabelEncoder()
    # Fit the LabelEncoder on the combined unique values from both train and test data
    le.fit(pd.concat([train[col], test[col]]).astype(str).unique())
    train[col] = le.transform(train[col].astype(str))
    test[col] = le.transform(test[col].astype(str))

In [24]:
train.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'RoadType',
       'NumberofLanes', 'LargeVehicles', 'Landmarks', 'Temperature', 'Weather',
       'hour', 'peak_hour', 'night'],
      dtype='object')

In [25]:
train.drop("Index", axis=1, inplace=True)

test.drop("Index", axis=1, inplace=True)

In [26]:
#Training the model

In [30]:
X = train.drop("demand", axis=1)
y = train["demand"]
# Drop the 'timestamp' column as it's an object type and features have been extracted
X = X.drop("timestamp", axis=1)

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
model = XGBRegressor(n_estimators=500,learning_rate=0.05,max_depth=8,subsample=0.8,colsample_bytree=0.8,random_state=42)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [35]:
val_preds = model.predict(X_test)

In [44]:
score=max(0,100*(r2_score(y_test, val_preds)))

In [45]:
print(score)

86.74489557691548

In [48]:
# Predict test data
# Drop the 'timestamp' column from the test DataFrame as it's an object type
test = test.drop("timestamp", axis=1)
test_preds = model.predict(test)
# Create submission dataframe
submission = pd.DataFrame({"Index": range(len(test_preds)),"demand": test_preds})

# Save CSV
submission.to_csv("submission.csv",index=False)

print("submission.csv created successfully")

submission.csv created successfully

In [49]:
df2=pd.read_csv('submission.csv')
print(df2.head())

   Index    demand
0      0  0.105790
1      1  0.075563
2      2  0.102601
3      3  0.130414
4      4  0.080691

In [52]:
r2 = r2_score(y_test,val_preds)
print(f"R2 Score: {r2}")

R2 Score: 0.8674489557691548